/**
 * SLO Summary Formatting - P14
 *
 * Formats SLO evaluation results for various outputs
 */

import { SLOEvaluationResult, SLOStatus } from './types';

/**
 * Redact sensitive values from text
 */
export function redactSensitiveData(text: string): string {
  const patterns = [
    { pattern: /(?:token|key|secret|password|auth|bearer)[:\s=]["']?[a-zA-Z0-9_.+/=-]{10,}/gi, replacement: '[REDACTED]' },
    { pattern: /ghp_[a-zA-Z0-9]{36}/g, replacement: '[REDACTED_GH_TOKEN]' },
    { pattern: /gho_[a-zA-Z0-9]{36}/g, replacement: '[REDACTED_GH_OAUTH]' },
    { pattern: /sk-[a-zA-Z0-9]{32,}/g, replacement: '[REDACTED_API_KEY]' },
    { pattern: /xoxb-[a-zA-Z0-9-]+/g, replacement: '[REDACTED_SLACK_BOT]' },
    { pattern: /xoxp-[a-zA-Z0-9-]+/g, replacement: '[REDACTED_SLACK_USER]' },
  ];

  let result = text;
  for (const { pattern, replacement } of patterns) {
    result = result.replace(pattern, replacement);
  }
  return result;
}

/**
 * Get status emoji
 */
function getStatusEmoji(status: SLOStatus): string {
  switch (status) {
    case 'ok':
      return '✅';
    case 'warn':
      return '⚠️';
    case 'critical':
      return '🚨';
  }
}

/**
 * Format evaluation result for console output
 */
export function formatForConsole(result: SLOEvaluationResult): string {
  const lines: string[] = [];

  lines.push('='.repeat(60));
  lines.push(`SLO Evaluation - ${getStatusEmoji(result.overallStatus)} ${result.overallStatus.toUpperCase()}`);
  lines.push('='.repeat(60));
  lines.push('');
  lines.push(`Timestamp: ${result.timestamp}`);
  if (result.refId) {
    lines.push(`Reference: ${result.refId}`);
  }
  lines.push('');

  lines.push('Checks:');
  lines.push('-'.repeat(40));
  for (const check of result.checks) {
    const emoji = getStatusEmoji(check.status);
    lines.push(`${emoji} ${check.name}: ${check.message}`);
  }
  lines.push('');

  lines.push(`Summary: ${result.summary}`);
  lines.push('='.repeat(60));

  return lines.join('\n');
}

/**
 * Format evaluation result for GitHub Issue comment (Markdown)
 */
export function formatForIssueComment(result: SLOEvaluationResult): string {
  const lines: string[] = [];

  const statusBadge =
    result.overallStatus === 'ok'
      ? '![OK](https://img.shields.io/badge/SLO-OK-green)'
      : result.overallStatus === 'warn'
        ? '![WARN](https://img.shields.io/badge/SLO-WARN-yellow)'
        : '![CRITICAL](https://img.shields.io/badge/SLO-CRITICAL-red)';

  lines.push(`## SLO Check ${statusBadge}`);
  lines.push('');
  lines.push(`**Time:** ${result.timestamp}`);
  if (result.refId) {
    lines.push(`**Reference:** \`${result.refId}\``);
  }
  lines.push('');

  // Summary table
  lines.push('| Check | Status | Value | Threshold |');
  lines.push('|-------|--------|-------|-----------|');
  for (const check of result.checks) {
    const emoji = getStatusEmoji(check.status);
    lines.push(`| ${check.name} | ${emoji} ${check.status} | ${check.currentValue} | ${check.threshold} |`);
  }
  lines.push('');

  // Action items for non-OK checks
  const failedChecks = result.checks.filter((c) => c.status !== 'ok');
  if (failedChecks.length > 0) {
    lines.push('### Recommended Actions');
    lines.push('');
    for (const check of failedChecks) {
      const action = getRecommendedAction(check.name, check.status);
      lines.push(`- **${check.name}**: ${action}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by SLO Check CLI_');

  return lines.join('\n');
}

/**
 * Get recommended action for a failed check
 */
function getRecommendedAction(checkName: string, status: SLOStatus): string {
  const actions: Record<string, Record<SLOStatus, string>> = {
    queue_size: {
      ok: '',
      warn: 'Monitor queue growth. Consider scaling workers.',
      critical: 'Immediate attention needed. Scale workers or investigate blocking jobs.',
    },
    waiting_approval: {
      ok: '',
      warn: 'Review pending approvals. Check Approval Watcher status.',
      critical: 'Approvals are stale. Investigate watcher or manually process approvals.',
    },
    dlq_new: {
      ok: '',
      warn: 'Review DLQ entries. Run `npm run jobs:dlq:triage`.',
      critical: 'High failure rate to DLQ. Investigate root causes immediately.',
    },
    failure_rate: {
      ok: '',
      warn: 'Investigate recent failures. Check logs for patterns.',
      critical: 'Critical failure rate. Consider pausing queue until resolved.',
    },
    circuit_breakers: {
      ok: '',
      warn: 'Some MCPs are unhealthy. Check downstream services.',
      critical: 'Multiple MCPs failing. Investigate infrastructure issues.',
    },
  };

  return actions[checkName]?.[status] || 'Investigate the issue.';
}

/**
 * Format evaluation result for JSON output
 */
export function formatForJSON(result: SLOEvaluationResult): string {
  return JSON.stringify(result, null, 2);
}

/**
 * Format short summary for alerts
 */
export function formatShortSummary(result: SLOEvaluationResult): string {
  const emoji = getStatusEmoji(result.overallStatus);
  const failedChecks = result.checks.filter((c) => c.status !== 'ok');

  if (failedChecks.length === 0) {
    return `${emoji} SLO OK - All checks passed`;
  }

  const issues = failedChecks.map((c) => `${c.name}(${c.status})`).join(', ');
  return `${emoji} SLO ${result.overallStatus.toUpperCase()}: ${issues}`;
}
